server:
  port: 1024
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    suffix: .html
    mode: HTML
