#prd配置文件
spring:
  profiles: prd

  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML5
  resources:
    static-locations: classpath:/static/,classpath:/templates/

server:
  port: 80

#mybatis配置
mybatis:
  mapper-locations: classpath*:/com/jzp/dao/mybatis/**Mapping.xml


