#dev properties
spring:
  #指定此配置为dev环境
  profiles: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  resources:
    static-locations: classpath:/static/,classpath:/templates/
#端口配置
server:
  port: 8088

#mybatis配置
mybatis:
  mapper-locations: classpath*:/com/jzp/dao/mybatis/**Mapping.xml

logging:
  config: classpath:logback.xml
